### ISSUE TITLE
✨Aufsetzen von Django 2.0

### ISSUE THREAD

**Issue by cmg-dev** [cmg-dev/django2_workshop#1]
1. Die Installationsanleitung gibt es [hier](https://docs.djangoproject.com/en/2.0/topics/install/).

1. Das erste Tutorial befindet sich [hier](https://docs.djangoproject.com/en/2.0/intro/tutorial01/).

1. Bitte die [Admin Sektion](https://docs.djangoproject.com/en/2.0/intro/tutorial02/#introducing-the-django-admin) auslassen.

   Diese werden wir im Workshop nicht brauchen.

**Comment by cmg-dev** [comment]
Hey @OskarZ :)

kannst du bitte einmal deinen Stand hier hinein schreiben?
Wie weit bist Du?

**Comment by Psycho-Andreas** [comment]
Hallo.
Ich habe die Nachricht leider erst gerade gelesen. Ich habe mich heute an einer neuen Website versucht und es mitlerweile auch geschafft dynamische Inhalte bzw., die der Datenbanken in einem template anzeigen zu lassen.
Die Datenbanken kann man außerdem über ein Formular ergänzen. Die einzelnen Unterkategorien der Seite sind über Buttons erreichbar.
